CREATE TABLE STUDENT2(STID INT PRIMARY KEY,STNAME VARCHAR2(10),STFEE NUMBER(10),STLOC VARCHAR2(10));
INSERT INTO STUDENT2 VALUES(1021,'HARIDAS',53605,'PANGRAS');
INSERT INTO STUDENT2 VALUES(1022,'SAGAR',450,'RALEGAON');
INSERT INTO STUDENT2 VALUES(1023,'NILESH',10700,'SAYKHEDA');
INSERT INTO STUDENT2 VALUES(1024,'LOKESH',55000,'YAVATMAL');
INSERT INTO STUDENT2 VALUES(1025,'SWAJAL',10200,'YAVATMAL');
SELECT * FROM STUDENT2;
ALTER TABLE STUDENT2 MODIFY STNAME VARCHAR2(10) NOT NULL;
ALTER TABLE STUDENT2 MODIFY STFEE NUMBER(11) NOT NULL;
ALTER TABLE STUDENT2 MODIFY STLOC VARCHAR2(10) NOT NULL;
DESC STUDENT2;
ALTER TABLE STUDENT2 ADD STREMARK VARCHAR2(10) UNIQUE;
ALTER TABLE STUDENT2 RENAME TO STMARK ;
DESC STUDENT2;
ALTER TABLE STMARK RENAME TO STUDENT2;
DESC STUDENT2;
SELECT * FROM STUDENT2;

CREATE TABLE STUDENT3(DEPTID INT NOT NULL,DEPTNAME VARCHAR2(10),STID INT PRIMARY  KEY);
INSERT INTO STUDENT3 VALUES(1,'COMPUTERENGG',1021);
INSERT INTO STUDENT3 VALUES(2,'COMPUTERENGG',1022);
INSERT INTO STUDENT3 VALUES(3,'AI&DS',1023);
INSERT INTO STUDENT3 VALUES(4,'MECHANICAL',1024);
INSERT INTO STUDENT3 VALUES(5,'ELECTRICAL',1025);
DESC STUDENT3;
ALTER TABLE STUDENT3 MODIFY DEPTNAME VARCHAR2(20) NOT NULL;
DESC STUDENT3;
SELECT * FROM STUDENT3;
INSERT INTO SUDENT2 VALUES(&STID,&STNAME,&STFEE,&STLOC);
ALTER TABLE STUDENT2 MODIFY STLOC VARCHAR2(20);

SELECT * FROM STUDENT2;
INSERT INTO STUDENT2 VALUES(1026,'SANKET',1150,'GADCHIROLI');
ALTER TABLE STUDENT2 DROP COLUMN STREMARK;
SELECT * FROM STUDENT2;
INSERT INTO STUDENT2 VALUES(&STID,&STNAME,&STFEE,&STLOC);
INSERT INTO STUDENT2 VALUES(1026,'SANKET',1150,'GDCHOROLI');
SELECT * FROM STUDENT2;
INSERT INTO STUDENT2 VALUES(&STID,&STNAME,&STFEE,&STLOC);
----------------------------------------------------------
--PERFORMING SOME OPERATIONS ON THE TABLES--
SELECT STID AS X,STNAME AS Y FROM STUDENT2 Z;
CREATE TABLE DUPLICATE1 AS SELECT * FROM STUDENT2 WHERE 1=2;
DESC DUPLICATE1;
SELECT * FROM DUPLICATE1;
CREATE TABLE ORIGIONAL1 AS SELECT * FROM STUDENT2 WHERE 1=1;
DESC ORIGIONAL1;
SELECT * FROM ORIGIONAL1;
DROP TABLE DUPLICATE1;
DROP TABLE ORIGIONAL1;

------------------------------------------

