CREATE TABLE  STUDENT(
STID INT,
SNAME VARCHAR2(10),
SFEE NUMBER(5)
);
SELECT * FROM TAB;
ALTER TABLE STUDENT MODIFY STUDENTNAME VARCHAR2(10);
ALTER TABLE STUDENT MODIFY SNAME VARCHAR2(20);

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD STUDENTADD VARCHAR2(10);

ALTER TABLE STUDENT RENAME COLUMN SNAME TO STDNAME;

ALTER TABLE STUDENT RENAME COLUMN STDNAME TO SNAME;

ALTER TABLE STUDENT DROP COLUMN STUDENTNAME;

ALTER TABLE STUDENT DROP COLUMN STUDENTADD;

RENAME STUDENT TO STD1;

SELECT * FROM STD1;

RENAME STD1 TO STUDENT;

SELECT * FROM STUDENT;

INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1021,'HARIDAS',79000);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1022,'ALEX',9000);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1023,'SAM',45000);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1024,'CARRY',6700);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1025,'SAMSUNG',3344);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1026,'DAVID',7800);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1027,'LOKESH',5600);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1028,'DHAMMA',9000);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1029,'JASON',7000);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES(1030,'MORGAN',8000);

SELECT * FROM STUDENT;
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES (&STID,&SNAME,&SFEE);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES (&STID,&SNAME,&SFEE);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES (&STID,&SNAME,&SFEE);
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES (&STID,&SNAME,&SFEE);

SELECT * FROM STUDENT;




