SELECT * FROM EMPLOYEES; 
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%Y';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%I%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'M%N';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_O%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%T%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%A';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'D%A';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'C%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'D%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%H%';
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%S';

SELECT EMPLOYEE_ID ,FIRST_NAME,SALARY,COMMISION,ABS(COMMISION-SALARY) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME,SALARY,COMMISION,ABS(COMMISION-SALARY) AS TOTAL_SALARY FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)<6;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)>7;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)>8;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)>9;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)>10;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)>11;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)<11;

SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)<11;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)=11;
SELECT * FROM EMPLOYEES WHERE LENGTH(LAST_NAME)<=11;

SELECT FIRST_NAME,LAST_NAME,LOWER(FIRST_NAME) FROM EMPLOYEES;
SELECT LAST_NAME,LOWER(LAST_NAME) FROM EMPLOYEES;

SELECT AVG(SALARY ) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT SUM(SALARY) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(LAST_NAME) FROM EMPLOYEES;
SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;
SELECT COUNT(SALARY) FROM EMPLOYEES;
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;

--SELCT *FROM EMPLOYEES WHERE FIRST_NAME='STEVEN';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME='STEVEN';
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='STEVEN';
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME='GUY';
SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME;
SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME DESC;
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES ORDER BY 3 DESC;
SELECT COUNT(*) FROM EMPLOYEES;

SELECT FIRST_NAME,COUNT(*) AS NO_OF_EMPLOYEES FROM EMPLOYEES  GROUP BY FIRST_NAME;
SELECT LAST_NAME,COUNT(*) AS NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY LAST_NAME;
SELECT SALARY,COUNT(*) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY SALARY;

SELECT PHONE_NUMBER,COUNT(*) AS EMP_PHONE_NUMBER FROM EMPLOYEES GROUP BY PHONE_NUMBER;

SELECT SALARY,COUNT(*) FROM EMPLOYEES GROUP BY SALARY HAVING COUNT(*)>3;

SELECT LAST_NAME,COUNT(*) FROM EMPLOYEES GROUP BY LAST_NAME HAVING COUNT(*)>6;

SELECT FIRST_NAME,COUNT(*) FROM EMPLOYEES GROUP BY FIRST_NAME HAVING COUNT(*)>3;

